{
  "comments": [
    {
      "key": {
        "uuid": "63dfbbb6_e069e72c",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/physical_interface.py",
        "patchSetId": 2
      },
      "lineNbr": 38,
      "author": {
        "id": 515
      },
      "writtenOn": "2020-04-10T20:43:06Z",
      "side": 1,
      "message": "it should be done as post_dbe_create or pre_dbe_create. I think PI will be created in DB even if post_dbe_create fails. Ideally, we should not create this PI in DB if ae_id is in use in DB",
      "revId": "073d4ee1d2390e9c0c42a82053db441692102aa7",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}