{
  "comments": [
    {
      "key": {
        "uuid": "c7f27447_717e8d03",
        "filename": "src/config/api-server/vnc_cfg_api_server/resources/global_system_config.py",
        "patchSetId": 4
      },
      "lineNbr": 205,
      "author": {
        "id": 10
      },
      "writtenOn": "2019-08-22T06:22:40Z",
      "side": 1,
      "message": "NoIdError exception is not an HTTP error and does no contains a status_code and content attribute. You should return 404 and the representation of the exception:\n\n return False, (404, str(e))",
      "range": {
        "startLine": 205,
        "startChar": 30,
        "endLine": 205,
        "endChar": 56
      },
      "revId": "293e80500f429f9df0c71659647967d9861d2e84",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}