{
  "comments": [
    {
      "key": {
        "uuid": "11f85cfa_408ab2ae",
        "filename": "src/config/api-server/vnc_cfg_api_server/event_dispatcher.py",
        "patchSetId": 6
      },
      "lineNbr": 75,
      "author": {
        "id": 56
      },
      "writtenOn": "2020-08-06T18:29:53Z",
      "side": 1,
      "message": "I think following case will fail,\n\n1. first client subscribed for fields X, Y\n2. Second client subscribed for fields X, Z\n3. Both client is unsubscribing at the same time\n\nCan you check this in a UT,",
      "revId": "9d1ea19a5871746b3a210caa95fdf5c1b2173c97",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "99979654_b14771ba",
        "filename": "src/config/api-server/vnc_cfg_api_server/tests/test_event_dispatcher.py",
        "patchSetId": 6
      },
      "lineNbr": 80,
      "author": {
        "id": 56
      },
      "writtenOn": "2020-08-06T18:26:49Z",
      "side": 1,
      "message": "why do we need try catch of gevent.timeout.Timeout",
      "revId": "9d1ea19a5871746b3a210caa95fdf5c1b2173c97",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a1e401a8_e5990a84",
        "filename": "src/config/api-server/vnc_cfg_api_server/tests/test_event_dispatcher.py",
        "patchSetId": 6
      },
      "lineNbr": 98,
      "author": {
        "id": 56
      },
      "writtenOn": "2020-08-06T18:26:49Z",
      "side": 1,
      "message": "WatcherQueue class can be moved out of the test class and reused in all tests",
      "revId": "9d1ea19a5871746b3a210caa95fdf5c1b2173c97",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    }
  ]
}