{
  "comments": [
    {
      "key": {
        "uuid": "33173d37_0a8d4eea",
        "filename": "src/config/common/cfgm_common/vnc_amqp.py",
        "patchSetId": 7
      },
      "lineNbr": 147,
      "author": {
        "id": 843
      },
      "writtenOn": "2020-06-18T09:33:30Z",
      "side": 1,
      "message": "in line 119 \u0027request_id\u0027 is used, self.create_msgbus_trace(self.oper_info.get(\u0027request_id\u0027),\n\nin line 147 \u0027request-id\u0027 used.\n\nany typo here?",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "2d54aa1d_8f6cdcc7",
        "filename": "src/config/common/cfgm_common/vnc_amqp.py",
        "patchSetId": 7
      },
      "lineNbr": 147,
      "author": {
        "id": 510
      },
      "writtenOn": "2020-06-19T16:40:43Z",
      "side": 1,
      "message": "Yes, that\u0027s a bug on line 119 which I\u0027d noticed before. Apparently its not used.",
      "parentUuid": "33173d37_0a8d4eea",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "8c430bf0_64efb24c",
        "filename": "src/config/device-manager/device_manager/db.py",
        "patchSetId": 7
      },
      "lineNbr": 57,
      "author": {
        "id": 843
      },
      "writtenOn": "2020-06-18T09:33:30Z",
      "side": 1,
      "message": "How about creating this on demand/in Feature DM it self? seems it\u0027s referenced only from the FeatureDM.",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "6a800d2c_f7741e5a",
        "filename": "src/config/device-manager/device_manager/db.py",
        "patchSetId": 7
      },
      "lineNbr": 57,
      "author": {
        "id": 510
      },
      "writtenOn": "2020-06-19T16:40:43Z",
      "side": 1,
      "message": "I will test this on a live system as soon as a system becomes available. If the code gets repeated, we can move it to a method as a bug fix in another review.",
      "parentUuid": "8c430bf0_64efb24c",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "41363d35_f6f90831",
        "filename": "src/config/device-manager/device_manager/db.py",
        "patchSetId": 7
      },
      "lineNbr": 177,
      "author": {
        "id": 843
      },
      "writtenOn": "2020-06-18T09:33:30Z",
      "side": 1,
      "message": "In case of update operation - looks we are fetching the same PR objects again (in the above API _calc_pr_id_set and here).\n\nif yes, is there any scope for fetching only one time - not sure of the impact.",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "8c946f67_0f1a1f2e",
        "filename": "src/config/device-manager/device_manager/db.py",
        "patchSetId": 7
      },
      "lineNbr": 177,
      "author": {
        "id": 510
      },
      "writtenOn": "2020-06-19T16:40:43Z",
      "side": 1,
      "message": "There is indeed a chance that the old list and new list both contain the same pr_id. That would have been resolved in line 174 so that the loop at line 176 will only go through each PR one time.",
      "parentUuid": "41363d35_f6f90831",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "d5cf765c_7739666b",
        "filename": "src/config/fabric-ansible/ansible-playbooks/module_utils/filter_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 203,
      "author": {
        "id": 843
      },
      "writtenOn": "2020-06-18T09:33:30Z",
      "side": 1,
      "message": "Do we need to take care in case of failure - either by clearing/adding a transaction info?",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": true
    },
    {
      "key": {
        "uuid": "a83d81fe_e639beb0",
        "filename": "src/config/fabric-ansible/ansible-playbooks/module_utils/filter_utils.py",
        "patchSetId": 7
      },
      "lineNbr": 203,
      "author": {
        "id": 510
      },
      "writtenOn": "2020-06-19T16:40:43Z",
      "side": 1,
      "message": "Since job transactions are a best effort attempt, I felt that ignoring any failure here would be better that failing an entire job (fabric delete, device delete, or role assignment).",
      "parentUuid": "d5cf765c_7739666b",
      "revId": "cfc27ba8defd151af4ec2f6b92b7f42326afe089",
      "serverId": "c72cd27d-1743-4a55-84a4-cd13b8400c52",
      "unresolved": false
    }
  ]
}